# Other settings like title, email, etc. may be above
- name: Generate Sitemap
  uses: cicirello/generate-sitemap@v1
  with:
    base-url-path: https://medixpharclub.com/   # <-- FORCE THIS VALUE
    # Add this line to ignore the default GitHub environment URL:
    # drop-sitemap-extension: false
